version: '3.8'

services:
  node1:
    container_name: raft3d_node1
    build: .
    environment:
      - NODE_ID=node1
      - RAFT_ADDR=node1:7000
      - HTTP_ADDR=0.0.0.0:8000
      - RAFT_DIR=/raft-data
    ports:
      - "8001:8000"
    volumes:
      - node1-data:/raft-data
    networks:
      raft3d-net:
        aliases:
          - node1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s  # Extended initialization time

  node2:
    container_name: raft3d_node2
    build: .
    environment:
      - NODE_ID=node2
      - RAFT_ADDR=node2:7000
      - HTTP_ADDR=0.0.0.0:8000
      - RAFT_DIR=/raft-data
    ports:
      - "8002:8000"
    volumes:
      - node2-data:/raft-data
    networks:
      raft3d-net:
        aliases:
          - node2
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  node3:
    container_name: raft3d_node3
    build: .
    environment:
      - NODE_ID=node3
      - RAFT_ADDR=node3:7000
      - HTTP_ADDR=0.0.0.0:8000
      - RAFT_DIR=/raft-data
    ports:
      - "8003:8000"
    volumes:
      - node3-data:/raft-data
    networks:
      raft3d-net:
        aliases:
          - node3
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  node1-data:
  node2-data:
  node3-data:

networks:
  raft3d-net: